export EDITOR='nvim'
export PATH="$PATH:$HOME/.local/bin:$CARGO_HOME/bin"
export XDG_CONFIG_HOME="$HOME/.config"
export ADOTDIR="$XDG_CONFIG_HOME/antigen"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
export RUSTUP_HOME="$XDG_CONFIG_HOME/rustup"
export AWT_TOOLKIT=MToolkit
export _JAVA_AWT_WM_NONREPARENTING=1
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
